### ISSUE TITLE
Display issues

### ISSUE THREAD

**Issue by Vereschagin** [kontur/fontsampler-wordpress-plugin#83] opened 2017-04-18 14:27 UTC
Hi, Johannes:

I'm back at redeveloping my website, but have run into a couple of issues. I am still working locally.

One issue is that the Fontsampler is not displaying in Safari. It is there, but not visible. It does show up in the Chrome, but the display is wonky.

What could be going wrong here?

Chrome:
![chrome screen shot 2017-04-18 at 9 59 28 am](https://cloud.githubusercontent.com/assets/10108357/25135840/732468f4-2421-11e7-9cca-7e3748d594bc.png)

Safari:
![safari screen shot 2017-04-18 at 9 59 43 am](https://cloud.githubusercontent.com/assets/10108357/25135839/72f3c776-2421-11e7-9b38-feeff85d054f.png)

**Comment by kontur** [comment] 2017-04-18 18:13
When a Fontsampler is "there" but invisible that usually points at the fonts not loading correctly, or some sort of Javascript error happening (either in the plugin or elsewhere). When you view your local development page, open the Safari developer console with alt+cmd+c, then go to the "Console" tab in the developer console, and then refresh the page - do you get any kind of errors there?

Are you by any chance using woff2 files exclusively? (They are currently available as option to the backend, but not working as expected)

Are you using the latest version of Fontsampler, or a previous? You can see that in the Wordpress admin area, under plugins, it should show the version of the installed plugin.

**Comment by kontur** [comment] 2017-04-18 18:29
It might also help if you could let me know the Safari version you are using. Safari > About

**Comment by Vereschagin** [comment] 2017-04-18 19:24
I'm attaching a text file of the console error log. I'm using Safari 10.1. I installed Fontsampler 0.2.2 this morning. WordPress 4.7.3.

[Console error log 2017 04 18.txt](https://github.com/kontur/fontsampler-wordpress-plugin/files/930831/Console.error.log.2017.04.18.txt)

**Comment by kontur** [comment] 2017-04-18 20:43
Hey, thanks for that info. It looks like there is a problem with Javascript, possibly from other plugins. A module loader I am using in my plugin has a potential for conflicts if other javascript pieces are loaded in a "non-conformant" way. It's quite likely that when you turn off other plugins (for example one-by-one and reload in between to determine which one is causing the problem) the Fontsampler will work again.
However, I've helped someone else debug this same issue once, and I would like to see if I could do something in my plugin to avoid this issue even if other plugins aren't playing nice - and to make sure this definitely isn't something I'm handling wrong in the Fontsampler plugin. So, what I would ask you is if you could let me know all plugins you have currently installed on your development version? I'll try to install them in a local test version as well and see if I can reproduce the problem then. You can also email me at hello@johannesneumeier.com if you don't want to post this publicly.

**Comment by Vereschagin** [comment] 2017-04-18 21:12
The other active plugins are:

a3 Portfolio
Advanced Code Editor
Disable Comments
Jetpack by WordPress.com
Simple 301 Redirects
Typekit fonts for WordPress

Deactivating any of the last five does not fix the problem. Unfortunately, deactivating a3 Portfolio causes all of the page content to be replaced by the a3 Porfolio shortcode that builds the page.

So… I duplicated the a3 Portfolio page as a regular WordPress page and deactivated all plugins except Fontsampler. Still no display. But the Console error log is much briefer:

[Error] SyntaxError (DOM Exception 12): The string did not match the expected pattern.
	(anonymous function) (WebfontProvider.js:78)
	_makeWebfont (WebfontProvider.js:78)
	_onLoadFont (WebfontProvider.js:100)
	(anonymous function)
	publish (PubSub.js:38)
	onLoadFont (loadFonts.js:34)
	onLoadFont

**Comment by kontur** [comment] 2017-04-19 07:43
Thanks for that info. I think there is two separate problems here. I've installed all the plugins you have and get the similar error messages. I will look into fixing this particular issue now that I can reproduce them better, however, those problems do not cause Fontsampler to break in my test, and the fonts render just fine despite the error logs from other plugins or conflicting javascript library definitions.

The console error you are now reporting, however, is something I can't reproduce. Looking at that spot in the code it looks like something with how the font is loaded by the browser or what font metadata (which gets extracted from the font file) is passed in to the browser on the load call is not quite as I'd expect it to be. Are you experiencing this issue with all woff fonts? Could you try a single publicly available woff file in a single fontsampler, for example from the "Webfont Kit" tab at [fontsquirrel](https://www.fontsquirrel.com/fonts/open-sans), download the @font-face kit, extract the zip and use the included woff file to upload to your test site? Does that font work, or do you get the same error? 
Since I can't reproduce this with any fonts available to me, would you be comfortable with emailing me (hello@johannesneumeier.com) one of the woff files that you experience this issue - with? Needless to say I will treat the file confidential, I will test it only locally on my computer, and delete the file when I am done testing. It's optional, but it might help me figure out why exactly the javascript breaks and fails to load the font.

**Comment by kontur** [comment] 2017-04-19 12:41
For the first error causing this load of console errors I have a preliminary fix available. I've not bumped the version number, so it's not installable via the Plugin menu, but you can [download the update as zip](https://github.com/kontur/fontsampler-wordpress-plugin/archive/0.2.2b.zip) and then place the contents of this archive in the /wp-content/plugins/fontsampler directory of your local test site to manually update the plugin.
Let me know if that takes care of the console errors on the "a3 portfolio" page (aside from that single one you reported above, which seems to be a different issue).

For the other issue I'm still depending on more feedback or test files from you.

**Comment by Vereschagin** [comment] 2017-04-19 13:31
The revised plugin fixed all the errors except for the WebfontProvider issue. I'll move on to doing tests with other fonts now. The Toronto Subway fonts that I am trying to use on that particular page were generated by FontSquirrel, though.

**Comment by kontur** [comment] 2017-04-19 13:41
Okay, great to hear the partial fix worked for your setup.

The portion of the code that the error appears on sets up the Webfont for the browser, and also passes in parameters for font name, weight, style and width. So while it sounds less likely that there is a problem if you have created those woffs with fontsquirrel, there still might be something in the font's tables that gets detected wrong by the plugin (and the underlying library I use for extracting those fields). In that sense trying with a verified font is just a measure to exclude this as the source of the problem, or to pin point more exactly what is the issue.

**Comment by Vereschagin** [comment] 2017-04-19 14:08
I downloaded Aleo from Font Squirrel and created a font sampler using the WOFF file for just the regular weight. Still no display at all in Safari, just a blank space where the sampler should be visible. Although during one page refresh something that might have been the font sampler flashed on the screen and then disappeared immediately when the rest of the page loaded.

Display in Chrome and Firefox is essentially unchanged. See the below screenshot from Chrome.

I'm going to try some testing using a different WP template.

![chrome screen shot 2017-04-19 at 10 01 34 am](https://cloud.githubusercontent.com/assets/10108357/25184228/dcfca57c-24e7-11e7-94b1-d066b3214bdd.png)

**Comment by kontur** [comment] 2017-04-19 14:19
It's hard to debug this remote, so forgive my naive questions.

So the screenshot, is that on safari or chrome, or do both look like this?

Do you have a default text set for the Fontsampler (like in below screenshot), or is it just that the "textarea" is empty - if you hover over the empty textarea (above the UI elements of the Fontsampler), do you get the "text input" cursor? When you click, can you actually type there?

<img width="1440" alt="screen shot 2017-04-19 at 17 18 27" src="https://cloud.githubusercontent.com/assets/1893577/25184840/3f2a673e-2524-11e7-8cf6-5cdd99d0d27a.png">

When you say "still no display, just a blank space where the sampler should be" - do you mean that the text input field of the Fontsampler is missing, or the entire Fontsampler including the UI elements (like the sliders and dropdowns etc).

One more thing, it could of course be that your theme overwrites some of the CSS declarations... this would have to be with "!important" statements, but it is an option nonetheless. When you inspect the actual Fontsampler element like in the below screenshot, what kind of CSS rules does it show on the element? In particular the top most "element" styles should be those generated by the plugin - is the font-family crossed out or deactivated?

<img width="1440" alt="screen shot 2017-04-19 at 17 15 27" src="https://cloud.githubusercontent.com/assets/1893577/25184722/ea1bed4e-2523-11e7-9b08-e0d3b2e61bbd.png">

**Comment by Vereschagin** [comment] 2017-04-19 14:49
That screenshot is from Chrome. Firefox looks the same. Safari still looks like the Safari screenshot I uploaded yesterday:

Safari:
![safari screen shot 2017-04-19 at 10 25 12 am](https://cloud.githubusercontent.com/assets/10108357/25185158/92729dec-24ea-11e7-80ea-db47c94a7e77.png)

Using the Web Inspector, it is clear that the elements are all there, just not visible. The default text in the text field can be changed. The sampler is there, but not visible.  I've now tried three other themes and the results in Safari are the same.

Here's a shot from Safari with the Web Inspector open. Something appears to be overriding the CSS that makes the sampler visible after it is loaded (fontsampler-css.css line 4265). And I can't find any font declarations whatsoever for the sampler.

![screen shot 2017-04-19 at 10 33 14 am](https://cloud.githubusercontent.com/assets/10108357/25185590/c1aa239a-24eb-11e7-8410-d688e25935ce.png)

**Comment by Vereschagin** [comment] 2017-04-19 14:54
Here's a shot from the Firefox Web Inspector, which more clearly shows the CSS for the sampler:

![screen shot 2017-04-19 at 10 52 23 am](https://cloud.githubusercontent.com/assets/10108357/25186534/730a28ea-24ee-11e7-87a2-0c8f1f47ca21.png)

**Comment by Vereschagin** [comment] 2017-04-19 20:17
I've put up a stripped-down version of the site and a test page. You can access it by going to <http://wordpress.quadrat.com>. There is a font sampler installed on the home page that should be using Aleo Regular. This page has the same display problems in Safari, Chrome and Firefox as my local one. Let me know if you'd like access to the backend.

**Comment by kontur** [comment] 2017-04-20 08:12
Thanks for the test setup. When you wrote earlier:

> I'm attaching a text file of the console error log. I'm using Safari 10.1. I installed Fontsampler 0.2.2 this morning. WordPress 4.7.3. **WOFF and WOFF2 fonts.**

I was assuming you are using woff2 and woff files for each font. Can you check if adding not only the woff2 but also the woff file fixes the issue? I was hoping/assuming woff2 support to already be implemented in a library I am using, and have opted to provide that option in the Fontsampler admin area to make the forward transition easy and encourage users to already add woff2. However, at the moment the woff2 files won't render as expected yet pending the implementation in the opentype.js library, so the woff "fallback" is needed.

**Comment by Vereschagin** [comment] 2017-04-20 12:13
Your assumption was correct: In my initial fontsampler I had a fontset using both WOFF and WOFF2 files for each of the four Toronto Subway fonts (i.e. eight files total for the four fonts). In the sampler on the page that is now online only one font is used: Aleo Regular and only a WOFF file.

Using only the WOFF files does not affect the display problems.

Oh, here's an interesting wrinkle: When I go into a fontset and remove the WOFF2 file, BOTH the WOFF and the WOFF2 file links are removed, although the files are not deleted from the uploads folder. If I then relink using the file that is already in the uploads folder, Fontsampler puts another copy of the font in the folder and uses that new copy. This seems wasteful.

Here's something else (I should probably be filing these as separate issues): If I choose a font from the fontset and set it as initial, save changes, then go back into the fontsampler, my choice of initial font has apparently been unset. There's no indication of which font I set to be the initial font.

**Comment by kontur** [comment] 2017-04-20 16:57
Okay. Now I think I have all the issues figured out.

1. Woff2 alone does not work, this is as expected, but I should point out this current lack of support more clearly
2. Opened issue #86 for erroneously deleting several font files when deleting one - should have a fix for this within a day
3. Deleting a fontfile will have an option to remove the actual file from the media library, when I get around to implementing #77
4. Not re-linking is the expected behaviour. I opened #87 to allow the option to pick an existing font file from the media gallery
5. The "initial" selected font not getting saves is a clear bug, probably a result of the 0.2.0 update that restructured a few things. I should have a fix for this within a day
6. **The reason your font is not rendering is because the file itself does not have a postscript or other name table font family name set.** #72 also is related to this, since the option to also overwrite this detected name would be nice. Equally, I would also want to detect and display those font internal names on font upload, so this could be flagged earlier and not cause this confusion. For now, the "simple" solution is to make sure the woff file you use does actually have font names set in the editing software. I haven't checked if the Fontsquirrel generator somehow automatically generates a woff with the font name removed (which would be terrible practice), but either way supplying fonts with full meta data would be desirable. When #72 and #57 get implemented I hope to address this issue and give proper error feedback to the admin.

Would you confirm that 6) is indeed a correct assumption? I.e. make sure you use a woff file you have generated with a font family name set in the editor that is used to export it? The [webfont @font-face kit](https://www.fontsquirrel.com/fonts/open-sans) I linked above has the correct family name and thus should work. 

Thanks for reporting all these issues. I'll to ship a bugfix update addressing some of them asap. I know it seems tedious that so many issues relating to the things you reported are already known and open still, but my time working on the plugin is unfortunately limited. That said, it's great to get to hear what are the most pressing problems to prioritise and fix.

**Comment by Vereschagin** [comment] 2017-04-20 18:03
I, too, find it bizarre to think that the Font Squirrel webfont generator would remove family names. The Toronto Subway source fonts definitely have font family names in them. 

I can't do any checking or any testing for the next few days, as I'm away from my computers. So, you'll have a break from my reports until Sunday at the earliest. I do appreciate the work you've put into the plugin so far and your quick responses to my postings.

**Comment by kontur** [comment] 2017-04-20 21:59
I just pushed version 0.2.3 to the Wordpress plugin registry and it will be available for updating to you. It fixes a whole bunch of issues you raised. However, the a) woff2 not working and b) detecting missing font name tables is still pending, since they are a little more complex. Once you get around to it testing some more, let me know if this is indeed the cause of the issue (i.e. verify against the sample font I linked).
Thanks again for all your feedback - I hope the plugin works out for you and, slowly but surely, will have all the features you wished for ;)

**Comment by Vereschagin** [comment] 2017-04-30 15:39
I've generated new webfonts using TransType rather than Font Squirrel. These seem to contain the necessary family names. 

I'm encountering cosmetic problems with the font names field/label. The screen shot below illustrates most of these problems.

1. The font name in default display is set too high and too tight to the left. Is there a way to adjust the margins/padding in the box?

2. The box for the font selection dropdown has a black background.  How can this be changed?

3. The font names in the drop down are offset to the right. I'm sure this is to provide some indenting from the active name, but it results in a clumsy-looking display.

4. The colour of the text in the font selection box is inheriting the colour from the other text labels. But this is not always desirable, as displayed in the attached screen shot. Can these colours be adjusted separately?

![screen shot 2017-04-30 at 11 35 59 am](https://cloud.githubusercontent.com/assets/10108357/25565672/923a1802-2d99-11e7-9b91-24b6fdd7c2d7.png)

**Comment by kontur** [comment] 2017-05-01 17:16
I'll check these styling issues asap, but an away from work this week, so earliest next week. It's possible some of the styling from a theme is overriding some of the styling of the plugin UI, so those I can address with more specific CSS declarations

**Comment by kontur** [comment] 2017-05-08 09:25
By the look of your preview wordpress installation on the subdomain you got the indenting issues of the drop down menus fixed already.
For the coloring of the the icon buttons as well as the default dropdown background I will add more interface options in an upcoming release. The drop down's item list you can already style from the settings, under _Settings > Options > Styling > Highlight color_.

For a hotfix you can overwrite the css also in your theme's custom css:
`.fontsampler-wrapper .selectric > * { background: ... }` for the dropdowns, and
`.fontsampler-wrapper .fontsampler-interface .fontsampler-multiselect > button { background: ... !important; }` for the buttons. This is temporary though, only until I can implement and publish the next update with those options available also in the admin interface.

**Comment by kontur** [comment] 2017-05-08 09:28
Opened issue #90 to address this. Missing or erroneous font family names in files will also be detected in the future.

**Comment by Vereschagin** [comment] 2017-05-09 15:11
Actually, I haven't made all the changes I've been tinkering with on the live preview site, so the dropdown menu problem persists. I'll get the preview updated and let you know when it's ready.

**Comment by Vereschagin** [comment] 2017-05-10 18:59
I've updated the preview site. The sample text should be 36px but is 14px. The problem with the background of the dropdown menu does not display, so I assume it is caused by a3 portfolio, which I'm using on my local site but not on  the online preview. Custom highlighting colours in the menu do not work. Text labels in the fontsampler should be at 80% of default text size, but are not. The font names should be "Toronto Subway" not "TorontoSubway". The "TorontoSubway" name must be coming from the font name records, instead from the names I've given them in the fontsampler. Toronto Subway Bold is identified as Toronto Subway SemiBold, although I set the naming option for Bold in TransType.

**Comment by kontur** [comment] 2017-05-14 09:37
A bunch of improvements coming with the next release, addressing some of these issues.
I've added css options for Dropdown base color, Icons are now colorizable as well, line-height in all UI labels can be set also.
I'll check locally again if the a3 portfolio interferes with the dropdown padding. This is most likely a css conflict.

Font names getting displayed as their file meta name for now, but I am working on an option to overwrite these. Stay tuned.

**Comment by Vereschagin** [comment] 2017-05-15 13:01
Don't spend too much time checking a3 portfolio. I've only been using it as a test and if it's a problem I can look into switching to something else to provide the capabilities I want. There are a lot of WP portfolio managers out there.

**Comment by kontur** [comment] 2017-05-21 12:21
Just rolled out 0.2.4 which should provide some more custom styling options for the settings. I'll keep this thread open, since a bunch of other issues were mentioned here that are not yet fixed with this update.

**Comment by Vereschagin** [comment] 2017-06-05 18:51
Hi, Johannes:

More on display issues. These are with version 0.2.5.

Size control not honouring initial value. I have the value set for 36 px both as default and in the custom settings for the particular fontsampler. Initial displayed size remains 40 px (incidentally the value in the interface layout preview).

Size control maximum cannot be set above 99 px by typing input. Anything above gets truncated to two digits. E.g. 120 px gets changed to 12 px. Setting the value using the slider works okay.

Line height control maximum cannot be set above 99% by typing input. Anything above get altered to two digits. E.g. 180% gets changed to 10%. Setting the value using the slider works okay, but is imprecise.

Display of OpenType features is using the normal CSS styling for page text instead of the sizes and colours set in the styling for Label text colour and Font size of the UI labels. There also needs to be some space between the selection boxes and their text labels.

**Comment by Vereschagin** [comment] 2017-07-13 13:44
Any update on the display of font names? This is a killer issue for me.

**Comment by kontur** [comment] 2017-07-14 11:02
The next time I find time to work on Fontsampler this is my first priority. I set myself a deadline for Sunday next week to at least start on it. It requires patching this possibility into one of the underlying libraries, so is a bit more complex than just me hacking it into Fontsampler.

**Comment by kontur** [comment] 2017-07-21 06:54
The next update will include allowing font names to be set explicitly via the Fontsampler menu and no longer will depend on the postscript names in the files themselves. I am just gathering some related fixes and enhancements before releasing this, but the update will come live within a week or so. Thanks for your patience with this issue, I appreciate it is very important to you.

**Comment by kontur** [comment] 2017-07-24 07:52
Please update to 0.3.3 and let me know if that works for you. :)

**Closed** 2017-10-18 19:49 UTC
Labels: bug, fixed in next release
